name: Generate API Client

on:
  push:
    branches:
      - main

jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Install NSwag and Swagger CLI
        run: |
          dotnet tool install -g NSwag.ConsoleCore
          dotnet tool install -g Swashbuckle.AspNetCore.Cli

      - name: Build API and Generate API Client
        run: npm run generate-api

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/apiClient.ts
          git commit -m "Updated API Client" || echo "No changes to commit"
          git push
